### ISSUE TITLE
Add room_list_publication_rules

### ISSUE THREAD

**Issue by nbuechner** [canonical/synapse-operator#162]
### Steps to reproduce

Publish a room on the ubuntu.com homeserver. The server allows this.

### Outcome

Only users on the whitelist are allowed to publish rooms on the ubuntu.com homeserver.
Please add this list of users to room_list_publication_rules in the homeserver.yaml to enable this limitation:

```

room_list_publication_rules:
 - user_id: "@n.buechner:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@ilvipero:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@merlijn-sebrechts:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@arraybolt3:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@seth-arnold:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@ulfnic:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@aaronprisk:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@kewisch:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@ravage:xentonix.net"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "@arraybolt3:matrix.org"
   alias: "*"
   room_id: "*"
 - user_id: "@kohutek:ubuntu.com"
   alias: "*"
   room_id: "*"
 - user_id: "@hggdh2:ubuntu.com"
   alias: "*"
   room_id: "*"
 - user_id: "@gschiano:ubuntu.com"
   alias: "*"
   room_id: "*"
   action: allow
 - user_id: "*"
   alias: "*"
   room_id: "*"
   action: deny

```
