### ISSUE TITLE
Display abuse reports in management room

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#97]
#### What would you like to do?
Abuse reports should show in the management room so we can potentially act on them.

#### How would you like to achieve it?
Enable `abuseReporting` and configure [reporting redirects](https://github.com/matrix-org/mjolnir/blob/main/test/nginx.conf):

```yaml
web:
  # Whether to enable web APIs.
  enabled: true

  # The port to expose the webserver on. Defaults to 8080.
  port: 8010

  # The address to listen for requests on. Defaults to only the current
  # computer.
  address: localhost

  # Alternative setting to open to the entire web. Be careful,
  # as this will increase your security perimeter:
  #
  #  address: "0.0.0.0"

  # A web API designed to intercept Matrix API
  # POST /_matrix/client/r0/rooms/{roomId}/report/{eventId}
  # and display readable abuse reports in the moderation room.
  #
  # If you wish to take advantage of this feature, you will need
  # to configure a reverse proxy, see e.g. test/nginx.conf
  abuseReporting:
    # Whether to enable this feature.
    enabled: true
```
