### ISSUE TITLE
Enable retention settings for media

### ISSUE THREAD

**Issue by kewisch** [canonical/synapse-operator#99]
### Your use case

Discuss and enable settings to limit retention for media. Example settings from another homeserver:

```yaml
# Retention
delete_stale_devices_after: 1y
media_retention:
  remote_media_lifetime: 14d
forgotten_room_retention_period: 14d
```
